### ISSUE TITLE
KeyError on preprocessing

### ISSUE THREAD

**Issue by weiSENshu** [PlusLabNLP/DEGREE#20]
I refer to the solution of # 17, in the data processing of dygiepp, modify the code to
`python ./scripts/data/ace-event/parse_ace_event.py [output-name] --include_entity_coreference --include_event_coreference`

**Comment by kissaxin572** [comment]
Did you solve the question? It doesn't seem to be because of this problem

**Comment by JJC-CH** [comment]
你好，请问一下解决这个问题了吗，我按照dygiepp的方法，运行了python ./scripts/data/ace-event/parse_ace_event.py default-settings和python scripts/data/shared/collate.py \
  data/ace-event/processed-data/default-settings/json \
  data/ace-event/collated-data/default-settings/json \
  --file_extension json，在DEGREE当中运行./scripts/process_ace05e.sh之后
出现了Traceback (most recent call last):
  File "preprocessing/process_ace05e.py", line 202, in <module>
    convert(args.input, args.output, bert_tokenizer, args.window)
  File "preprocessing/process_ace05e.py", line 41, in convert
    coref_entities = doc['clusters']
KeyError: 'clusters'错误，请问一下您是咋解决的这个问题

**Comment by JJC-CH** [comment]
> I refer to the solution of # 17, in the data processing of dygiepp, modify the code to `python ./scripts/data/ace-event/parse_ace_event.py [output-name] --include_entity_coreference --include_event_coreference`

Do we still need the following two configurations, or can we do without them?
--include_times_and_values \
--include_pronouns
